### ISSUE TITLE
Why SNMP V1?

### ISSUE THREAD

**Issue by tgrymatt** [NETWAYS/check_akcp#1]
Hi @dnsmichi ,

why you are using SNMP v1 and not v3? Are there any special reasons?

**Comment by tgrymatt** [comment]
Forget it. Plugin is years old. No wonder that this is SNMP v1 ;)

**Comment by dnsmichi** [comment]
No special reasons. v3 works different with authentication though, and is harder to maintain. AFAIK AKCP requires an additional license to fully get v3 support too.
