### ISSUE TITLE
[Question] Checking negative values in a cold storage room

### ISSUE THREAD

**Issue by MarcusCaepio** [NETWAYS/check_akcp#2]
Hi all, 
we want to use a AKCP Sensor to check the negative temperature of a cold storage room (Round about -20°C). 
The sensor itself works between -55 and 75 °C. But does the plugin also work with negative values?

Cheers,
Marcus

**Comment by mxhash** [comment]
Hi!

Took a quick look over the source and there is nothing special about the value. What is the raw value if you do a snmpwalk over the device? Do you see negative numbers there?

**Comment by MarcusCaepio** [comment]
Unfortunately we haven't installed the sensor yet. That's why I am asking :) We would like to know if this plugin is usable, before we are installing it :)

**Comment by mxhash** [comment]
So in this case: Yes works out ;-)

Cheers,
Marius
